# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-30 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20180130_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='category.Category'),
        ),
    ]
